version: 0.2

phases:
  install:
    commands:
      # Check for Python 3.x
      - python3 --version
      # Install pip3 if not available
      - apt-get update
      - apt-get install -y python3-pip
      # Upgrade pip and setuptools
      - pip3 install --upgrade pip setuptools
      # Check pip3 version
      - pip3 --version
      # Install Flask using pip3
      - pip3 install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python3 test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
